### ISSUE TITLE
Extract raw poetry file from github link

### ISSUE THREAD

**Issue by Kilo59** [Kilo59/ruff-sync#12]
Given a link to a pryoject.toml hosted on github such as https://github.com/great-expectations/great_expectations/blob/develop/pyproject.toml I should be able to pass that link as my  `upstream` parameter and it should work.

Currently this only works if I link to the "raw" file. https://raw.githubusercontent.com/great-expectations/great_expectations/develop/pyproject.toml

## Strech goal

Allow for `upstream` link to a github repo that contains a `pyproject.toml`

**Comment by dustinbowers** [comment]
I'll leave the stretch goal to someone else :P

**Comment by dustinbowers** [comment]
By the way, I just discovered a more robust way to support github-like URLs.  Instead of doing string replaces on a github-specific url to get the raw url, it's easier to just add a `?raw=1` query string parameter. Using this approach would add support for repositories on websites other than just github.com (as long as they support the same query parameter)

For example:
https://github.com/great-expectations/great_expectations/blob/develop/pyproject.toml becomes
https://github.com/great-expectations/great_expectations/blob/develop/pyproject.toml?raw=1

This requires an additional parameter in `client.get(url)` to follow redirects: `client.get(url, follow_redirects=True)`
